### ISSUE TITLE
Crashes when a window is moved to the scratchpad

### ISSUE THREAD

**Issue by alfredjophy** [WillPower3309/swayblur#11]
Here's the traceback

```
Traceback (most recent call last):
  File "/usr/sbin/swayblur", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/swayblur/__main__.py", line 122, in main
    blurManager.start()
  File "/usr/lib/python3.10/site-packages/swayblur/blurManager.py", line 92, in start
    self.SWAY.main()
  File "/usr/lib/python3.10/site-packages/i3ipc/connection.py", line 514, in main
    raise loop_exception
  File "/usr/lib/python3.10/site-packages/i3ipc/connection.py", line 497, in main
    while not self._event_socket_poll():
  File "/usr/lib/python3.10/site-packages/i3ipc/connection.py", line 477, in _event_socket_poll
    raise e
  File "/usr/lib/python3.10/site-packages/i3ipc/connection.py", line 474, in _event_socket_poll
    self._pubsub.emit(event_name, event)
  File "/usr/lib/python3.10/site-packages/i3ipc/_private/pubsub.py", line 28, in emit
    s['handler'](self.conn, data)
  File "/usr/lib/python3.10/site-packages/swayblur/blurManager.py", line 97, in handleMove
    containerOutput = container.workspace().ipc_data['output']
KeyError: 'output'
```

**Comment by WillPower3309** [comment]
Thanks for the report! I will fix this tomorrow, I know exactly what the issue is here

**Comment by alfredjophy** [comment]
Its fixed...updated in the AUR

**Comment by alfredjophy** [comment]
Minor issue...if a app is launched directly into the scratchpad
```
for_window [app_id="FFPWA-01FFKCF7GFET9F2VCJDNNFD1FJ"] move scratchpad
```

opening such an app leads to a crash

Traceback

```
Blurred wallpaper exists for eDP-1
Listening...
'output'
Traceback (most recent call last):
  File "/usr/sbin/swayblur", line 33, in <module>
    sys.exit(load_entry_point('swayblur==1.1.1', 'console_scripts', 'swayblur')())
  File "/usr/lib/python3.10/site-packages/swayblur/__main__.py", line 125, in main
    blurManager.start()
  File "/usr/lib/python3.10/site-packages/swayblur/blurManager.py", line 91, in start
    self.SWAY.main()
  File "/usr/lib/python3.10/site-packages/i3ipc/connection.py", line 514, in main
    raise loop_exception
  File "/usr/lib/python3.10/site-packages/i3ipc/connection.py", line 497, in main
    while not self._event_socket_poll():
  File "/usr/lib/python3.10/site-packages/i3ipc/connection.py", line 477, in _event_socket_poll
    raise e
  File "/usr/lib/python3.10/site-packages/i3ipc/connection.py", line 474, in _event_socket_poll
    self._pubsub.emit(event_name, event)
  File "/usr/lib/python3.10/site-packages/i3ipc/_private/pubsub.py", line 28, in emit
    s['handler'](self.conn, data)
  File "/usr/lib/python3.10/site-packages/swayblur/blurManager.py", line 125, in handleNew
    self.outputs[workspace.ipc_data['output']].blur()
KeyError: 'output'
```

**Comment by WillPower3309** [comment]
Thanks for the update, I'll look into that. I thought I finally squashed the scratchpad bugs! Should be an easy fix though
